language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
  - master
before_install:
  - pip install pytest-cov
  - pip install coveralls
install: "pip install -r requirements.txt"
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: py.test
after_success:
  - coveralls
