language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
  - master
sudo: required
before_install:
  - sudo apt-get install tree
install: "pip install -r requirements.txt"
script: pwd && tree && py.test
